Split honeycomb into honeycomb and hc2vpp
Change-Id: I5d55ab2adf8a7feadae7fe99d31a170f2e145d29
Signed-off-by: Maros Marsalek <mmarsale@cisco.com>

diff --git a/jjb/hc2vpp/hc2vpp.yaml b/jjb/hc2vpp/hc2vpp.yaml
--- a/jjb/hc2vpp/hc2vpp.yaml
+++ b/jjb/hc2vpp/hc2vpp.yaml
@@ -1,24 +1,28 @@
 - project:
-    name: honeycomb
+    name: hc2vpp
     jobs:
-        - 'honeycomb-verify-{stream}-{os}'
-        - 'honeycomb-merge-{stream}-{os}'
-        - 'honeycomb-benchmark-master'
-    project: 'honeycomb'
+        - 'hc2vpp-verify-{stream}-{os}'
+        - 'hc2vpp-merge-{stream}-{os}'
+        - 'hc2vpp-integration-{stream}-{os}'
+        - 'hc2vpp-verify-image-{stream}-{os}'
+    project: 'hc2vpp'
     os:
+        - ubuntu1404:
+            repo-os-part: 'ubuntu.trusty.main'
+            skip-site: 'false'
         - ubuntu1604:
             repo-os-part: 'ubuntu.xenial.main'
+            skip-site: 'true'
+        - centos7:
+            repo-os-part: 'centos7'
             skip-site: 'true'
     stream:
         - master:
             branch: 'master'
             repo-stream-part: 'master'
-        - '1609':
-            branch: 'stable/1609'
-            repo-stream-part: 'stable.1609'
 
 - job-template:
-    name: 'honeycomb-verify-{stream}-{os}'
+    name: 'hc2vpp-verify-{stream}-{os}'
     project-type: maven
     node: verify-{os}
     concurrent: true
@@ -50,7 +54,7 @@
 
     triggers:
         - gerrit-trigger-patch-submitted:
-            name: 'honeycomb'
+            name: 'hc2vpp'
             branch: '{branch}'
 
     prebuilders:
@@ -61,17 +65,83 @@
         root-pom: 'pom.xml'
         goals: 'clean install -V -Dmaven.repo.local=/tmp/r -Dorg.ops4j.pax.url.mvn.localRepository=/tmp/r  -Dmerge -Dkaraf.keep.unpack=true site'
         maven-opts: '-Xmx2048m -Dmaven.compile.fork=true'
-        settings: 'honeycomb-settings'
+        settings: 'hc2vpp-settings'
         settings-type: cfp
         global-settings: 'global-settings'
         global-settings-type: cfp
 
     publishers:
         - email-notification:
-            email-prefix: '[honeycomb]'
+            email-prefix: '[hc2vpp]'
 
 - job-template:
-    name: 'honeycomb-merge-{stream}-{os}'
+    name: 'hc2vpp-verify-image-{stream}-{os}'
+    project-type: maven
+    node: 'verify-image-{os}'
+    concurrent: true
+    jdk: openjdk8-{os}
+
+    logrotate:
+        daysToKeep: '{build-days-to-keep}'
+        numToKeep: '{build-num-to-keep}'
+        artifactDaysToKeep: '{build-artifact-days-to-keep}'
+        artifactNumToKeep: '{build-artifact-num-to-keep}'
+
+    parameters:
+        - project-parameter:
+            project: '{project}'
+        - gerrit-parameter:
+            branch: '{branch}'
+        - os-parameter:
+            os: '{os}'
+
+    scm:
+        - gerrit-trigger-scm:
+            credentials-id: 'jenkins-gerrit-credentials'
+            refspec: '$GERRIT_REFSPEC'
+            choosing-strategy: 'gerrit'
+
+    wrappers:
+        - fdio-infra-wrappers:
+            build-timeout: '{build-timeout}'
+
+    triggers:
+        - gerrit:
+            server-name: 'Primary'
+            trigger-on:
+                - comment-added-contains-event:
+                    comment-contains-value: 'verify-images'
+            projects:
+              - project-compare-type: 'ANT'
+                project-pattern: '{project}'
+                branches:
+                  - branch-compare-type: 'ANT'
+                    branch-pattern: '**/{branch}'
+            skip-vote:
+                successful: true
+                failed: true
+                unstable: true
+                notbuilt: true
+
+    prebuilders:
+        - shell: |
+            if [ "${{OS}}" == "ubuntu1404" ];then sudo update-java-alternatives -s /usr/lib/jvm/java-1.8.0-openjdk-amd64||echo 'ignoring failure';fi
+    maven:
+        maven-name: 'mvn33'
+        root-pom: 'pom.xml'
+        goals: 'clean install -V -Dmaven.repo.local=/tmp/r -Dorg.ops4j.pax.url.mvn.localRepository=/tmp/r  -Dmerge -Dkaraf.keep.unpack=true'
+        maven-opts: '-Xmx2048m -Dmaven.compile.fork=true'
+        settings: 'hc2vpp-settings'
+        settings-type: cfp
+        global-settings: 'global-settings'
+        global-settings-type: cfp
+
+    publishers:
+        - email-notification:
+            email-prefix: '[hc2vpp]'
+
+- job-template:
+    name: 'hc2vpp-merge-{stream}-{os}'
     project-type: maven
     node: merge-{os}
     jdk: openjdk8-{os}
@@ -107,7 +177,7 @@
 
     triggers:
         - gerrit-trigger-patch-merged:
-            name: 'honeycomb'
+            name: 'hc2vpp'
             branch: '{branch}'
 
     maven:
@@ -115,22 +185,10 @@
         root-pom: 'pom.xml'
         goals: 'clean install -V -Dmaven.repo.local=/tmp/r -Dorg.ops4j.pax.url.mvn.localRepository=/tmp/r  -Dmerge -Dkaraf.keep.unpack=true -Dsonar -Dmaven.site.skip={skip-site} site -Dmaven.site.deploy.skip={skip-site} site:deploy'
         maven-opts: '-Xmx2048m -Dmaven.compile.fork=true'
-        settings: 'honeycomb-settings'
+        settings: 'hc2vpp-settings'
         settings-type: cfp
         global-settings: 'global-settings'
         global-settings-type: cfp
-
-    postbuilders:
-        - maven-target:
-            maven-version: 'mvn33'
-            goals: '--version'
-            settings: 'honeycomb-settings'
-            settings-type: cfp
-            global-settings: 'global-settings'
-            global-settings-type: cfp
-        - provide-maven-settings:
-            settings-file: 'honeycomb-settings'
-            global-settings-file: 'global-settings'
 
     reporters:
         - findbugs
@@ -141,17 +199,13 @@
             language: 'java'
             branch: '{stream}'
         - email-notification:
-            email-prefix: '[honeycomb]'
-        - maven-deploy:
-            id: ''
-            unique-version: true
-            deploy-unstable: false
+            email-prefix: '[hc2vpp]'
 
 - job-template:
-    name: 'honeycomb-benchmark-master'
+    name: 'hc2vpp-integration-{stream}-{os}'
     project-type: maven
-    node: verify-ubuntu1604
-    jdk: openjdk8-ubuntu1604
+    node: merge-{os}
+    jdk: openjdk8-{os}
 
     logrotate:
         daysToKeep: '{build-days-to-keep}'
@@ -163,17 +217,17 @@
         - project-parameter:
             project: '{project}'
         - os-parameter:
-            os: 'ubuntu1604'
+            os: '{os}'
         - maven-project-parameter:
             maven: 'mvn33'
         - repo-name-parameter:
-            repo-name: 'master.ubuntu.xenial.main'
+            repo-name: '{repo-stream-part}.{repo-os-part}'
 
     scm:
-        - gerrit-trigger-scm:
+        - git-scm:
             credentials-id: 'jenkins-gerrit-credentials'
             refspec: ''
-            choosing-strategy: 'default'
+            branch: '{branch}'
 
     wrappers:
         - ssh-agent-credentials:
@@ -183,31 +237,46 @@
             build-timeout: '{build-timeout}'
 
     triggers:
-        - timed: '@daily'
+        - reverse:
+            jobs: 'vpp-merge-{stream}-{os},hc2vpp-merge-{stream}-{os}'
+            result: 'success'
+
+    prebuilders:
+        - shell: |
+            if [ "${{OS}}" == "ubuntu1404" ];then sudo update-java-alternatives -s /usr/lib/jvm/java-1.8.0-openjdk-amd64||echo 'ignoring failure';fi
 
     maven:
         maven-name: 'mvn33'
         root-pom: 'pom.xml'
-        goals: 'clean install -V -Dmaven.repo.local=/tmp/r -Dorg.ops4j.pax.url.mvn.localRepository=/tmp/r  -Dmerge -Pbenchmark'
+        goals: 'clean install -V -Dmaven.repo.local=/tmp/r -Dorg.ops4j.pax.url.mvn.localRepository=/tmp/r  -Dmerge -Dkaraf.keep.unpack=true'
         maven-opts: '-Xmx2048m -Dmaven.compile.fork=true'
-        settings: 'honeycomb-settings'
+        settings: 'hc2vpp-settings'
         settings-type: cfp
         global-settings: 'global-settings'
         global-settings-type: cfp
 
+    postbuilders:
+        - maven-target:
+            maven-version: 'mvn33'
+            goals: '--version'
+            settings: 'hc2vpp-settings'
+            settings-type: cfp
+            global-settings: 'global-settings'
+            global-settings-type: cfp
+        - provide-maven-settings:
+            settings-file: 'hc2vpp-settings'
+            global-settings-file: 'global-settings'
+        - shell:
+            !include-raw-escape:
+                - ../scripts/maven_push_functions.sh
+                - include-raw-hc2vpp-pkg-push.sh
+    reporters:
+        - findbugs
+
     publishers:
-        - plot:
-            - title: 'Infrastructure CFG write benchmark'
-              yaxis: 'ops/second'
-              csv-file-name: 'benchmark.csv'
-              group: 'infra-bench'
-              keep-records: true
-              numbuilds: '20'
-              style: 'line'
-              use-description: false
-              series:
-                - file: 'infra/it/benchmark/target/benchmark.csv'
-                  display-table: true
-                  format: 'csv'
-                  inclusion-flag: 'include-by-string'
-                  exclude: 'Score'
+        - email-notification:
+            email-prefix: '[hc2vpp]'
+        - maven-deploy:
+            id: ''
+            unique-version: true
+            deploy-unstable: false
