CSIT-56: Automated run of Honeycomb tests
- Update 'csit-honeycomb-functional-{stream}-{os}' job to the
  latest changes.

Change-Id: I904423a4f55c11007aa7ba1a0268642a103ab699
Signed-off-by: Tibor Frank <tifrank@cisco.com>

diff --git a/jjb/csit/csit-vpp-honeycomb.yaml b/jjb/csit/csit-vpp-honeycomb.yaml
--- a/jjb/csit/csit-vpp-honeycomb.yaml
+++ b/jjb/csit/csit-vpp-honeycomb.yaml
@@ -10,8 +10,11 @@
     stream:
         - master:
             branch: 'master'
-            branch-id: 'master'
-    os:
+            repo-stream-part: 'master'
+        - '1609':
+            branch: 'stable/1609'
+            repo-stream-part: 'stable.1609'
+    OS:
         - ubuntu1404
 
 - job-template:
@@ -39,17 +42,21 @@
                 - '{ssh-credentials}'
 
     triggers:
-        - build-result:
-            combine: false
-            groups:
-                - jobs:
-                    - honeycomb-merge-{stream}-{os}
-                  results:
-                    - success
+        - reverse:
+            jobs: 'honeycomb-integration-{stream}-ubuntu{OS}'
+            result: 'success'
 
+    prebuilders:
+        - shell: |
+            if [ "${{OS}}" == "ubuntu1404" ];then sudo update-java-alternatives -s /usr/lib/jvm/java-1.8.0-openjdk-amd64||echo 'ignoring failure';fi
+            
     builders:
         - shell:
             !include-raw-escape: include-raw-csit-honeycomb-functional-virl.sh
+
+    postbuilders:
+        - shell: |
+            if [ "${{OS}}" == "ubuntu1404" ];then sudo update-java-alternatives -s /usr/lib/jvm/java-1.7.0-openjdk-amd64||echo 'ignoring failure';fi
 
     publishers:
         - archive-artifacts:
