Ignoring failure in update-java-alternatives
* The script fails, though the failure can be ignored.

http://askubuntu.com/questions/599105/using-alternatives-with-java-7-and-java-8-on-14-04-2-lts

Change-Id: Ie7b70fb189505a46b6640f1a961001f0c75a21b5
Signed-off-by: C.J. Collier <cjcollier@linuxfoundation.org>

diff --git a/jjb/honeycomb/honeycomb.yaml b/jjb/honeycomb/honeycomb.yaml
--- a/jjb/honeycomb/honeycomb.yaml
+++ b/jjb/honeycomb/honeycomb.yaml
@@ -55,7 +55,7 @@
 
     prebuilders:
         - shell: |
-            if [ "${{OS}}" == "ubuntu1404" ];then sudo update-java-alternatives -s /usr/lib/jvm/java-1.8.0-openjdk-amd64;fi
+            if [ "${{OS}}" == "ubuntu1404" ];then sudo update-java-alternatives -s /usr/lib/jvm/java-1.8.0-openjdk-amd64||echo 'ignoring failure';fi
     maven:
         maven-name: '{mvn33}'
         root-pom: 'pom.xml'
@@ -68,7 +68,7 @@
 
     postbuilders:
         - shell: |
-            if [ "${{OS}}" == "ubuntu1404" ];then sudo update-java-alternatives -s /usr/lib/jvm/java-1.7.0-openjdk-amd64;fi
+            if [ "${{OS}}" == "ubuntu1404" ];then sudo update-java-alternatives -s /usr/lib/jvm/java-1.7.0-openjdk-amd64||echo 'ignoring failure';fi
 
     publishers:
         - email-notification:
@@ -126,7 +126,7 @@
 
     prebuilders:
         - shell: |
-            if [ "${{OS}}" == "ubuntu1404" ];then sudo update-java-alternatives -s /usr/lib/jvm/java-1.8.0-openjdk-amd64;fi
+            if [ "${{OS}}" == "ubuntu1404" ];then sudo update-java-alternatives -s /usr/lib/jvm/java-1.8.0-openjdk-amd64||echo 'ignoring failure';fi
     maven:
         maven-name: '{mvn33}'
         root-pom: 'pom.xml'
@@ -139,7 +139,7 @@
 
     postbuilders:
         - shell: |
-            if [ "${{OS}}" == "ubuntu1404" ];then sudo update-java-alternatives -s /usr/lib/jvm/java-1.7.0-openjdk-amd64;fi
+            if [ "${{OS}}" == "ubuntu1404" ];then sudo update-java-alternatives -s /usr/lib/jvm/java-1.7.0-openjdk-amd64||echo 'ignoring failure';fi
 
     publishers:
         - email-notification:
@@ -185,7 +185,7 @@
 
     prebuilders:
         - shell: |
-            if [ "${{OS}}" == "ubuntu1404" ];then sudo update-java-alternatives -s /usr/lib/jvm/java-1.8.0-openjdk-amd64;fi
+            if [ "${{OS}}" == "ubuntu1404" ];then sudo update-java-alternatives -s /usr/lib/jvm/java-1.8.0-openjdk-amd64||echo 'ignoring failure';fi
 
     maven:
         maven-name: '{mvn33}'
@@ -199,7 +199,7 @@
 
     postbuilders:
         - shell: |
-            if [ "${{OS}}" == "ubuntu1404" ];then sudo update-java-alternatives -s /usr/lib/jvm/java-1.7.0-openjdk-amd64;fi
+            if [ "${{OS}}" == "ubuntu1404" ];then sudo update-java-alternatives -s /usr/lib/jvm/java-1.7.0-openjdk-amd64||echo 'ignoring failure';fi
 
     reporters:
         - findbugs
@@ -250,7 +250,7 @@
 
     prebuilders:
         - shell: |
-            if [ "${{OS}}" == "ubuntu1404" ];then sudo update-java-alternatives -s /usr/lib/jvm/java-1.8.0-openjdk-amd64;fi
+            if [ "${{OS}}" == "ubuntu1404" ];then sudo update-java-alternatives -s /usr/lib/jvm/java-1.8.0-openjdk-amd64||echo 'ignoring failure';fi
 
     maven:
         maven-name: '{mvn33}'
@@ -278,7 +278,7 @@
                 - ../scripts/maven_push_functions.sh
                 - include-raw-honeycomb-pkg-push.sh
         - shell: |
-            if [ "${{OS}}" == "ubuntu1404" ];then sudo update-java-alternatives -s /usr/lib/jvm/java-1.7.0-openjdk-amd64;fi
+            if [ "${{OS}}" == "ubuntu1404" ];then sudo update-java-alternatives -s /usr/lib/jvm/java-1.7.0-openjdk-amd64||echo 'ignoring failure';fi
 
     reporters:
         - findbugs
